# Generated by Django 4.1.2 on 2022-11-04 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_club_player"),
    ]

    operations = [
        migrations.RemoveField(model_name="club_games", name="club_id",),
        migrations.RemoveField(model_name="club_master", name="user_id",),
        migrations.RemoveField(model_name="club_player", name="club_id",),
        migrations.RemoveField(model_name="club_player", name="player_id",),
        migrations.RemoveField(model_name="player_club_history", name="club_id",),
        migrations.RemoveField(model_name="player_club_history", name="player_id",),
        migrations.RemoveField(model_name="player_info", name="club_id",),
        migrations.RemoveField(model_name="player_info", name="country_id",),
        migrations.RemoveField(model_name="player_match_history", name="player_id",),
        migrations.RemoveField(model_name="user_details", name="user_id",),
        migrations.RemoveField(model_name="user_query", name="user_id",),
        migrations.AddField(
            model_name="club_games",
            name="club",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.club_master",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club_master",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user_login",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club_player",
            name="club",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.club_master",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="club_player",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.player_info",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player_club_history",
            name="club",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.club_master",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player_club_history",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.player_info",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player_info",
            name="club",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.club_master",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player_info",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.country_master",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player_match_history",
            name="player",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.player_info",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_details",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user_login",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user_query",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="myapp.user_login",
            ),
            preserve_default=False,
        ),
    ]
