# Generated by Django 4.1.2 on 2022-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0003_remove_club_games_club_id_remove_club_master_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country_master",
            name="budget",
            field=models.FloatField(default=2000000),
        ),
    ]
