# Generated by Django 4.1.4 on 2023-01-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_playerrequests_clubrequests"),
    ]

    operations = [
        migrations.CreateModel(
            name="club_notifications",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("url", models.URLField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.club_master",
                    ),
                ),
            ],
        ),
    ]
