# Generated by Django 4.1.4 on 2023-01-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_club_notifications"),
    ]

    operations = [
        migrations.AddField(
            model_name="club_notifications",
            name="heading",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
