# Generated by Django 4.2 on 2024-10-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_club_games_id_alter_club_master_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_master',
            name='c_flag',
            field=models.ImageField(upload_to='club_logos/'),
        ),
    ]
