# Generated by Django 4.2 on 2024-11-07 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_club_master_c_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_master',
            name='c_flag',
            field=models.CharField(max_length=250),
        ),
    ]
